# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The JustMinecraft Blog
email: perry@frasers.org
author: Perry Fraser
description: >
  TODO: This is a description, foo bar foo yay
  some longer text, wrapping Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias consequuntur rerum reprehenderit illum. Nostrum, minus molestiae, voluptatum dolorem quo quos aspernatur distinctio odit qui, repudiandae enim praesentium in dolores unde?
baseurl: "/JMBlog"
url: "" # the base hostname & protocol for your site, e.g. http://example.com (Do I need to use this?)
twitter_username: apachicraft

permalink: /:title

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
